/*
   Author: Vlad Seryakov vlad@crystalballinc.com
   January 2002
*/

INSERT INTO ossweb_apps (title, project_name, app_name, page_name, image)
       VALUES ('Locations', '*', 'contact', 'address', 'home.gif');

INSERT INTO ossweb_apps (title, project_name, app_name, page_name, image)
       VALUES ('People', '*', 'contact', 'people', 'user.gif');

INSERT INTO ossweb_apps (title, project_name, app_name, page_name, image)
       VALUES ('Companies', '*', 'contact', 'companies', 'group.gif');

INSERT INTO ossweb_apps (title, project_name, app_name, page_name, image, group_id)
       VALUES ('Contact Types', '*', 'contact', 'contacttypes', 'computer.gif', 1);

INSERT INTO ossweb_apps (title, project_name, app_name, page_name, image, group_id)
       VALUES ('Location Types', '*', 'contact', 'locationtypes', 'home.gif', 1);

INSERT INTO ossweb_reftable (app_name,page_name,table_name,object_name,title)
       VALUES('contact','addressunits','ossweb_address_units','unit','Address Unit');

INSERT INTO ossweb_reftable (app_name,page_name,table_name,object_name,title,refresh,precedence)
       VALUES('contact','addressstates','ossweb_address_states','state','Postal States','ADDR:S','Y');

INSERT INTO ossweb_reftable (app_name,page_name,table_name,object_name,title,refresh,extra_name,extra_label)
       VALUES('contact','streettypes','ossweb_street_types','type','Street Type','ADDR:ST','short_name','Short Name');

INSERT INTO ossweb_reftable (app_name,page_name,table_name,object_name,title,refresh)
       VALUES('contact','countries','ossweb_countries','country','Country','ADDR:C');

INSERT INTO ossweb_reftable (app_name,page_name,table_name,object_name,title,refresh)
       VALUES('contact','contacttypes','ossweb_contact_types','type','Contact Type','ADDR:CT');


INSERT INTO ossweb_location_types(type_id,type_name,precedence,address_check,number_check,street_check,unit_check,city_check,state_check,country_check,lot_check)
       VALUES('Address','Address',0,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE);

INSERT INTO ossweb_location_types(type_id,type_name,precedence,type_check,name_check,address_check,number_check,street_check,unit_check,city_check,state_check,country_check)
       VALUES('Warehouse','Warehouse',1,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE,TRUE);

INSERT INTO ossweb_location_types(type_id,type_name,precedence,type_check,name_check)
       VALUES('Mobile','Mobile',2,TRUE,TRUE);

INSERT INTO ossweb_location_types (type_id,type_name,precedence,type_check,name_check)
       VALUES('Location','Location',3,TRUE,TRUE);

INSERT INTO ossweb_address_units (unit_id,unit_name) VALUES('apt','Apartment');
INSERT INTO ossweb_address_units (unit_id,unit_name) VALUES('floor','Floor');
INSERT INTO ossweb_address_units (unit_id,unit_name) VALUES('suite','Suite');
INSERT INTO ossweb_address_units (unit_id,unit_name) VALUES('building','Building');
INSERT INTO ossweb_address_units (unit_id,unit_name) VALUES('pobox','PO BOX');

INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('AL','Alabama',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('AK','Alaska',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('AZ','Arizona',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('AR','Arkansas',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('CA','California',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('CO','Colorado',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('CT','Connecticut',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('DE','Delaware',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('DC','District of Columbia',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('FL','Florida',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('GA','Georgia',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('HI','Hawaii',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('ID','Idaho',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('IL','Illinois',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('IN','Indiana',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('IA','Iowa',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('KS','Kansas',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('KY','Kentucky',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('LA','Louisiana',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('ME','Maine',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('MD','Maryland',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('MA','Massachusetts',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('MI','Michigan',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('MN','Minnesota',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('MS','Mississippi',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('MO','Missouri',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('MT','Montana',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NE','Nebraska',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NV','Nevada',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NH','New Hampshire',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NJ','New Jersey',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NM','New Mexico',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NY','New York',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NC','North Carolina',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('ND','North Dakota',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('OH','Ohio',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('OK','Oklahoma',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('OR','Oregon',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('PA','Pennsylvania',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('PR','Puerto Rico',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('RI','Rhode Island',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('SC','South Carolina',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('SD','South Dakota',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('TN','Tennessee',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('TX','Texas',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('UT','Utah',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('VT','Vermont',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('VA','Virginia',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('WA','Washington',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('WV','West Virginia',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('WI','Wisconsin',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('WY','Wyoming',1);
INSERT INTO ossweb_address_states (state_id,state_name,precedence)VALUES('Canada','--- Canada ---',2);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('AB','Alberta',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('BC','British Columbia',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('MB','Manitoba',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NB','New Brunswick',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NF','Newfoundland',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NT','Northwest Territories',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('NS','Nova Scotia',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('ON','Ontario',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('PE','Prince Edward Island',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('QC','Quebec',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('SK','Saskatchewan',3);
INSERT INTO ossweb_address_states (state_id,state_name,precedence) VALUES('YT','Yukon',3);

INSERT INTO ossweb_countries (country_name,country_id) VALUES('Afghanistan','AF');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Albania','AL');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Algeria','DZ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('American Samoa','AS');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Andorra','AD');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Angola','AO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Anguilla','AI');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Antarctica','AQ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Antigua and Barbuda','AG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Argentina','AR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Armenia','AM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Aruba','AW');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Australia','AU');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Austria','AT');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Azerbaijan','AZ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Bahamas','BS');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Bahrain','BH');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Bangladesh','BD');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Barbados','BB');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Belarus','BY');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Belgium','BE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Belize','BZ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Benin','BJ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Bermuda','BM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Bhutan','BT');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Bolivia','BO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Bosnia and Herzegovina','BA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Botswana','BW');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Bouvet island','BV');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Brazil','BR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('British Indian Ocean Territory','IO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Brunei darussalam','BN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Bulgaria','BG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Burkina Faso','BF');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Burundi','BI');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Cambodia','KH');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Cameroon','CM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Canada','CA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Cape Verde','CV');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Cayman Islands','KY');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Central African Republic','CF');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Chad','TD');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Chile','CL');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('China','CN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Christmas Island','CX');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Cocos Islands','CC');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Colombia','CO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Comoros','KM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Congo','CG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Congo, The Democratic Republic Of The','CD');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Cook Islands','CK');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Costa Rica','CR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Cote D''Ivoire','CI');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Croatia','HR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Cuba','CU');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Cyprus','CY');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Czech Republic','CZ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Denmark','DK');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Djibouti','DJ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Dominica','DM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Dominican Republic','DO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('East Timor','TP');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Ecuador','EC');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Egypt','EG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('El Salvador','SV');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Equatorial Guinea','GQ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Eritrea','ER');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Estonia','EE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Ethiopia','ET');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Falkland Islands (Malvinas)','FK');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Faroe Islands','FO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Fiji','FJ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Finland','FI');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('France','FR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('French Guiana','GF');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('French Polynesia','PF');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('French Southern Territories','TF');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Gabon','GA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Gambia','GM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Georgia','GE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Germany','DE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Ghana','GH');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Gibraltar','GI');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Greece','GR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Greenland','GL');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Grenada','GD');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Guadeloupe','GP');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Guam','GU');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Guatemala','GT');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Guinea','GN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Guinea-Bissau','GW');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Guyana','GY');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Haiti','HT');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Heard Island And Mcdonald Islands','HM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Holy See (Vatican City State)','VA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Honduras','HN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Hong Kong','HK');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Hungary','HU');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Iceland','IS');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('India','IN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Indonesia','ID');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Iran, Islamic Republic Of','IR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Iraq','IQ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Ireland','IE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Israel','IL');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Italy','IT');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Jamaica','JM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Japan','JP');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Jordan','JO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Kazakhstan','KZ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Kenya','KE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Kiribati','KI');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Korea, Democratic People''s Republic Of','KP');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Korea, Republic Of','KR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Kuwait','KW');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Kyrgyzstan','KG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Lao People''s Democratic Republic','LA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Latvia','LV');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Lebanon','LB');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Lesotho','LS');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Liberia','LR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Libyan Arab Jamahiriya','LY');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Liechtenstein','LI');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Lithuania','LT');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Luxembourg','LU');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Macau','MO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Macedonia, The Former Yugoslav Republic Of','MK');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Madagascar','MG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Malawi','MW');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Malaysia','MY');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Maldives','MV');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Mali','ML');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Malta','MT');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Marshall Islands','MH');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Martinique','MQ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Mauritania','MR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Mauritius','MU');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Mayotte','YT');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Mexico','MX');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Micronesia, Federated States Of','FM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Moldova, Republic Of','MD');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Monaco','MC');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Mongolia','MN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Montserrat','MS');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Morocco','MA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Mozambique','MZ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Myanmar','MM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Namibia','NA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Nauru','NR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Nepal','NP');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Netherlands','NL');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Netherlands Antilles','AN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('New Caledonia','NC');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('New Zealand','NZ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Nicaragua','NI');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Niger','NE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Nigeria','NG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Niue','NU');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Norfolk Island','NF');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Northern Mariana Islands','MP');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Norway','NO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Oman','OM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Pakistan','PK');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Palau','PW');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Palestinian Territory, Occupied','PS');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Panama','PA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Papua new Guinea','PG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Paraguay','PY');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Peru','PE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Philippines','PH');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Pitcairn','PN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Poland','PL');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Portugal','PT');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Puerto Rico','PR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Qatar','QA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Reunion','RE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Romania','RO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Russian Federation','RU');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Rwanda','RW');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Saint Helena','SH');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Saint Kitts And Nevis','KN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Saint Lucia','LC');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Saint Pierre And Miquelon','PM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Saint Vincent And The Grenadines','VC');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Samoa','WS');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('San Marino','SM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Sao Tome And Principe','ST');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Saudi Arabia','SA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Senegal','SN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Seychelles','SC');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Sierra Leone','SL');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Singapore','SG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Slovakia','SK');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Slovenia','SI');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Solomon Islands','SB');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Somalia','SO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('South Africa','ZA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('South Georgia','GS');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Spain','ES');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Sri Lanka','LK');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Sudan','SD');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Suriname','SR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Svalbard And Jan Mayen','SJ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Swaziland','SZ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Sweden','SE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Switzerland','CH');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Syrian Arab Republic','SY');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Taiwan, Province Of China','TW');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Tajikistan','TJ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Tanzania, United Republic Of','TZ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Thailand','TH');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Togo','TG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Tokelau','TK');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Tonga','TO');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Trinidad And Tobago','TT');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Tunisia','TN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Turkey','TR');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Turkmenistan','TM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Turks And Caicos Islands','TC');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Tuvalu','TV');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Uganda','UG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Ukraine','UA');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('United Arab Emirates','AE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('United Kingdom','GB');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('United States','US');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('United States Islands','UM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Uruguay','UY');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Uzbekistan','UZ');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Vanuatu','VU');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Venezuela','VE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Viet Nam','VN');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Virgin Islands, British','VG');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Virgin Islands, U.S.','VI');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Wallis And Futuna','WF');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Western Sahara','EH');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Yemeh','YE');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Yugoslavia','YU');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Zambia','ZM');
INSERT INTO ossweb_countries (country_name,country_id) VALUES('Zimbabwe','ZW');

INSERT INTO ossweb_street_types(type_id,type_name,reverse_flag,nostreet_flag)
       VALUES('PO BOX','PO BOX',TRUE,TRUE);
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Alley','Alley','ALY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Annex','Annex','ANX');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Arcade','Arcade','ARC');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Avenue','Avenue','AVE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Autoroute','Autoroute',NULL);
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Bayou','Bayou','BYU');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Beach','Beach','BCH');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Bend','Bend','BND');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Bluff','Bluff','BLF');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Bluffs','Bluffs','BLFS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Bottom','Bottom','BTM');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Boulevard','Boulevard','BLVD');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Branch','Branch','BR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Bridge','Bridge','BRG');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Brook','Brook','BRK');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Brooks','Brooks','BRKS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Burg','Burg','BG');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Burgs','Burgs','BGS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Bypass','Bypass','BYP');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Camp','Camp','CP');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Canyon','Canyon','CYN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Cape','Cape','CPE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Causeway','Causeway','CSWY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Center','Center','CTR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Centers','Centers','CTRS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Circle','Circle','CIR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Circles','Circles','CIRS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Cliff','Cliff','CLF');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Cliffs','Cliffs','CLFS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Club','Club','CLB');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Common','Common','CMN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Commons','Commons','CMNS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Corner','Corner','COR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Corners','Corners','CORS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Course','Course','CRSE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Court','Court','CT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Courts','Courts','CTS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Cove','Cove','CV');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Coves','Coves','CVS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Creek','Creek','CRK');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Crescent','Crescent','CRES');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Crest','Crest','CRST');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Crossing','Crossing','XING');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Crossings','Crossings','XINGS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Crossroad','Crossroad','XRD');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Crossroads','Crossroads','XRDS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Curve','Curve','CURV');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Dale','Dale','DL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Dam','Dam','DM');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Divide','Divide','DV');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Drive','Drive','DR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Drives','Drives','DRS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Estate','Estate','EST');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Estates','Estates','ESTS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Expressway','Expressway','EXPY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Extension','Extension','EXT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Extensions','Extensions','EXTS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Fall','Fall','FALL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Falls','Falls','FLS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Ferry','Ferry','FRY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Field','Field','FLD');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Fields','Fields','FLDS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Flat','Flat','FLT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Flats','Flats','FLTS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Ford','Ford','FRD');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Fords','Fords','FRDS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Forest','Forest','FRST');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Forge','Forge','FRG');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Forges','Forges','FRGS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Fork','Fork','FRK');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Forks','Forks','FRKS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Fort','Fort','FT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Freeway','Freeway','FWY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Garden','Garden','GDN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Gardens','Gardens','GDNS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Gateway','Gateway','GTWY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Glen','Glen','GLN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Glens','Glens','GLNS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Green','Green','GRN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Greens','Greens','GRNS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Grove','Grove','GRV');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Groves','Groves','GRVS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Harbor','Harbor','HBR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Harbors','Harbors','HBRS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Haven','Haven','HVN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Heights','Heights','HTS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Highway','Highway','HWY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Hill','Hill','HL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Hills','Hills','HLS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Hollow','Hollow','HOLW');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Inlet','Inlet','INLT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Island','Island','IS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Islands','Islands','ISS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Isle','Isle','ISLE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Junction','Junction','JCT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Junctions','Junctions','JCTS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Key','Key','KY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Keys','Keys','KYS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Knoll','Knoll','KNL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Knolls','Knolls','KNLS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Lake','Lake','LK');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Lakes','Lakes','LKS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Land','Land','LAND');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Landing','Landing','LNDG');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Lane','Lane','LN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Light','Light','LGT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Lights','Lights','LGTS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Loaf','Loaf','LF');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Lock','Lock','LCK');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Locks','Locks','LCKS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Lodge','Lodge','LDG');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Loop','Loop','LOOP');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Mall','Mall','MALL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Manor','Manor','MNR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Manors','Manors','MNRS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Meadow','Meadow','MDW');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Meadows','Meadows','MDWS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Mill','Mill','ML');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Mills','Mills','MLS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Mission','Mission','MSN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Motorway','Motorway','MTWY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Mount','Mount','MT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Mountain','Mountain','MTN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Mountains','Mountains','MTNS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Neck','Neck','NCK');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Orchard','Orchard','ORCH');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Oval','Oval','OVAL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Overpass','Overpass','OPAS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Park','Park','PARK');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Parks','Parks','PARKS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Parkway','Parkway','PKWY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Parkways','Parkways','PKWYS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Pass','Pass','PASS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Passage','Passage','PSGE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Path','Path','PATH');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Pike','Pike','PIKE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Pine','Pine','PNE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Pines','Pines','PNES');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Place','Place','PL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Plain','Plain','PLN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Plains','Plains','PLNS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Plaza','Plaza','PLZ');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Point','Point','PT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Points','Points','PTS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Port','Port','PRT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Ports','Ports','PRTS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Prairie','Prairie','PR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Prospect','Prospect','PRSP');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Radial','Radial','RADL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Ramp','Ramp','RAMP');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Ranch','Ranch','RNCH');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Rapid','Rapid','RPD');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Rapids','Rapids','RPDS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Rest','Rest','RST');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Ridge','Ridge','RDG');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Ridges','Ridges','RDGS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('River','River','RIV');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Road','Road','RD');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Roads','Roads','RDS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Route','Route','RTE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Row','Row','ROW');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Rue','Rue','RUE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Run','Run','RUN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Shoal','Shoal','SHL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Shoals','Shoals','SHLS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Shore','Shore','SHR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Shores','Shores','SHRS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Skyway','Skyway','SKWY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Spring','Spring','SPG');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Springs','Springs','SPGS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Spur','Spur','SPUR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Spurs','Spurs','SPURS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Square','Square','SQ');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Squares','Squares','SQS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Station','Station','STA');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Stravenue','Stravenue','STRA');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Stream','Stream','STRM');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Street','Street','ST');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Streets','Streets','STS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Summit','Summit','SMT');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Terrace','Terrace','TER');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Throughway','Throughway','TRWY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Trace','Trace','TRCE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Track','Track','TRAK');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Trafficway','Trafficway','TRFY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Trail','Trail','TRL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Trailer','Trailer','TRLR');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Tunnel','Tunnel','TUNL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Turnpike','Turnpike','TPKE');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Underpass','Underpass','UPAS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Union','Union','UN');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Unions','Unions','UNS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Valley','Valley','VLY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Valleys','Valleys','VLYS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Viaduct','Viaduct','VIA');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('View','View','VW');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Views','Views','VWS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Village','Village','VLG');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Villages','Villages','VLGS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Ville','Ville','VL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Vista','Vista','VIS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Walk','Walk','WALK');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Walks','Walks','WALKS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Wall','Wall','WALL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Way','Way','WAY');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Ways','Ways','WAYS');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Well','Well','WL');
INSERT INTO ossweb_street_types(type_id,type_name,short_name) VALUES('Wells','Wells','WLS');
