-include ../Makefile.ossweb

install_links:
	ln -sf ../admin/reftable2.adp usstates.adp
	ln -sf ../admin/reftable2.tcl usstates.tcl
	ln -sf ../admin/reftable2.tcl addressunits.tcl
	ln -sf ../admin/reftable2.adp addressunits.adp
	ln -sf ../admin/reftable2.tcl streettypes.tcl
	ln -sf ../admin/reftable2.adp streettypes.adp
	ln -sf ../admin/reftable2.tcl contacttypes.tcl
	ln -sf ../admin/reftable2.adp contacttypes.adp

install:        install_module


