-include ../Makefile.ossweb

install:	install_module

links:
	ln -sf reftable.adp msgs.adp
	ln -sf reftable.tcl msgs.tcl
	ln -sf reftable2.adp usertypes.adp
	ln -sf reftable2.tcl usertypes.tcl
	ln -sf reftable2.adp configtypes.adp
	ln -sf reftable2.tcl configtypes.tcl
