-include ../Makefile.ossweb

install:        install_module


install_links:
	${install_dir} ${project_dir}/maverix
	${call install_file,pub/*,/${project_dir}/maverix}	
	${call install_file,doc/*,/${app_dir}/}	

