-include ../Makefile.ossweb

dirs:
	${install_dir} ${modules_dir}/files/shopping
	${install_link} ${modules_dir}/files/shopping ${html_dir}/${project}/shopping/images

install:        install_module


