-include ../Makefile.ossweb

links:
	${remove_file} ${app_dir}/images
	${install_dir} ${modules_dir}/files/${appname}
	${install_link} ${modules_dir}/files/${appname} ${app_dir}/images

install:        install_module


